import sbt._
import sbt.Keys._

object AbBuild extends Build {
  val scalazVersion = "7.1.0"

  val deps = List(
    "org.scalaz" %% "scalaz-core" % scalazVersion,
    "org.specs2" %% "specs2" % "2.4.15" % "test",
    "org.scalacheck" %% "scalacheck" % "1.12.2" % "test"
  )

  // from http://tpolecat.github.io/2014/04/11/scalac-flags.html
  val pedanticScalac = Seq(
    "-deprecation",           
    "-encoding", "UTF-8",       
    "-feature",                
    "-language:existentials",
    "-language:higherKinds",
    "-language:implicitConversions",
    "-unchecked",
    "-Xfatal-warnings",       
    "-Xlint",
    "-Yno-adapted-args",       
    "-Ywarn-dead-code",        
    "-Ywarn-numeric-widen",   
    "-Ywarn-value-discard",
    "-Xfuture",
    "-Ywarn-unused-import"     
  )

  val autoGenerated = Def.task {
    def createAlphaNum(file: File): Seq[File] = {
      val name = "AlphaNum"

      def className(c: Char): String = {
        if      (c.isDigit) "_" + c
        else if (c.isLower) "Lower" + c.toUpper
        else                "Upper" + c.toUpper
      }

      val chars = ('a' to 'z') ++ ('A' to 'Z') ++ ('0' to '9')

      val string = 
        """|package ab.model
           |
           |import scalaz._, Scalaz._
           |
           |/*
           | * Autogenerated by AbBuild.scala
           | */
           |sealed abstract class AlphaNum
           |object AlphaNum {
           |  def fromChar(c: Char): Option[AlphaNum] = c match {""".stripMargin('|') +
        chars.map { c =>
          s"    case '$c' => ${className(c)}.some"
        }.mkString("\n") + "\n" +
        """|    case other => none
           |  }
           |}
           |""".stripMargin('|') +
        chars.map { c =>
          s"case object ${className(c)} extends AlphaNum"
        }.mkString("\n")

      IO.write(file, string)

      List(file)
    }

    val file = (sourceManaged in Compile).value / "model" / s"AlphaNum.scala"
    createAlphaNum(file)
  }

  lazy val ab = Project(
    id = "ab",
    base = file("."),
    settings = Project.defaultSettings ++ Seq(
      name := "ab",
      organization := "ab",
      version := "0.1-SNAPSHOT",
      scalaVersion := "2.11.5",
      scalacOptions ++= pedanticScalac,
      libraryDependencies ++= deps,
      sourceGenerators in Compile += autoGenerated.taskValue
      // add other settings here
    )
  )
}
